### Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

### Toolchain setup
java.version=21

### Project
type=MOD
license=MIT
author=communi-suggestu
modId=saeculariacaudices
description=Library mod which patches in handling of complex block entity aware block properties.
owner=communi-suggestu
title=Saecularia Caudices

### Minecraft
minecraft.version=1.21.1
minecraft.additionalVersions=

### Parchment
parchment.version=2024.11.13
parchment.minecraftVersion=1.21.1

### Neoforge
neoforge.version=21.1.+
neoforge.runs.data=data

### Fabric
fabric.loader.version=0.16.7
fabric.api.version=0.114.0

### Versioning
local.version=1.21.1-local

### Dependency versioning
jetbrains.annotations.version=+