### Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

### Toolchain setup
java.version=25

### Project
project.type=MOD
project.owner=communi-suggestu

### Minecraft
minecraft.version=26.1.2
minecraft.additionalVersions=

### Common
common.neoform.version=26.1.2-1

### Neoforge
neoforge.version=[26.1.2.13-beta, 26.2)
neoforge.data.runs=clientData

### Fabric
fabric.loader.version=[0.19.2,)
fabric.api.version=0.148.0
fabric.api.minecraft.version=26.1.2

### Versioning
local.version=26.1.2-local

### Dependency versioning
jetbrains.annotations.version=+