modLoader="lowcodefml"
loaderVersion="[4,)"
license="GLGPLv3"

[[mods]] #mandatory
modId="saeculariacaudices"
version="${version}"
displayName="Saecularia Caudices"
authors="OrionOnline"
logoFile="logo-forge.png"
description='''
Library mod that makes blocks properties world aware
'''
[[dependencies.saeculariacaudices]]
modId="minecraft"
required=true
versionRange="${minecraft.version.get()}"
ordering="NONE"
side="BOTH"
[[dependencies.saeculariacaudices]]
modId="neoforge"
required=true
versionRange="${loader.version.get()}"
ordering="NONE"
side="BOTH"
[[mixins]]
config="sc.mixins.json"